name: main-workflow
run-name: ${{ github.actor }} is testing changes
on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: Flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8 ./ -v
  mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run mypy
        run: mypy ./
  pytest:
    runs-on: ubuntu-latest
    name: PyTest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest -v
